<?php

use Illuminate\Database\Seeder;
use App\Models\Keyword;

class KeywordSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Keyword::truncate();
        Keyword::insert([
            [ 'name' => 'rumah' ],
            [ 'name' => 'data' ],
            [ 'name' => 'pengumpulan' ],
            [ 'name' => 'analisis' ],
            [ 'name' => 'display' ],
            [ 'name' => 'sarasehan' ],
            [ 'name' => 'rembuk' ],
            [ 'name' => 'penyediaan' ],
            [ 'name' => 'administrasi' ],
            [ 'name' => 'kependudukan' ],
            [ 'name' => 'akta' ],
            [ 'name' => 'akte' ],
            [ 'name' => 'lahir' ],
            [ 'name' => 'mati' ],
            [ 'name' => 'kawin' ],
            [ 'name' => 'nikah' ],
            [ 'name' => 'cerai' ],
            [ 'name' => 'pindah' ],
            [ 'name' => 'KK' ],
            [ 'name' => 'kartu' ],
            [ 'name' => 'surat' ],
            [ 'name' => 'buku' ],
            [ 'name' => 'KTP' ],
            [ 'name' => 'KIA' ],
            [ 'name' => 'identitas' ],
            [ 'name' => 'advokasi' ],
            [ 'name' => 'sosialisasi' ],
            [ 'name' => 'KIE' ],
            [ 'name' => 'pelatihan' ],
            [ 'name' => 'pendampingan' ],
            [ 'name' => 'motivasi' ],
            [ 'name' => 'hidup' ],
            [ 'name' => 'sehat' ],
            [ 'name' => 'bersih' ],
            [ 'name' => 'germas' ],
            [ 'name' => 'olga' ],
            [ 'name' => 'olah' ],
            [ 'name' => 'raga' ],
            [ 'name' => 'konsumsi' ],
            [ 'name' => 'sayur' ],
            [ 'name' => 'buah' ],
            [ 'name' => 'rokok' ],
            [ 'name' => 'lingkungan' ],
            [ 'name' => 'jamban' ],
            [ 'name' => 'periksa' ],
            [ 'name' => 'kesehatan' ],
            [ 'name' => 'keluarga' ],
            [ 'name' => 'berencana' ],
            [ 'name' => 'KB' ],
            [ 'name' => 'Persalinan' ],
            [ 'name' => 'Faskes' ],
            [ 'name' => 'RS' ],
            [ 'name' => 'Puskesmas' ],
            [ 'name' => 'klinik' ],
            [ 'name' => 'Imunisasi' ],
            [ 'name' => 'ASI' ],
            [ 'name' => 'pertumbuhan' ],
            [ 'name' => 'perkembangan' ],
            [ 'name' => 'TBC' ],
            [ 'name' => 'Paru' ],
            [ 'name' => 'hipertensi' ],
            [ 'name' => 'darting' ],
            [ 'name' => 'darah' ],
            [ 'name' => 'ODGJ' ],
            [ 'name' => 'gila' ],
            [ 'name' => 'gangguan' ],
            [ 'name' => 'jiwa' ],
            [ 'name' => 'JKN' ],
            [ 'name' => 'BPJS' ],
            [ 'name' => 'jaminan' ],
            [ 'name' => 'air' ],
            [ 'name' => 'kelas' ],
            [ 'name' => 'BKB' ],
            [ 'name' => 'balita' ],
            [ 'name' => '1000' ],
            [ 'name' => 'HPK' ],
            [ 'name' => 'poktan' ],
            [ 'name' => 'hari' ],
            [ 'name' => 'pertama' ],
            [ 'name' => 'kehidupan' ],
            [ 'name' => 'pola' ],
            [ 'name' => 'asuh' ],
            [ 'name' => 'partisipasi' ],
            [ 'name' => 'ikut' ],
            [ 'name' => 'anak' ],
            [ 'name' => 'bayi' ],
            [ 'name' => 'baduta' ],
            [ 'name' => 'remaja' ],
            [ 'name' => 'konseling' ],
            [ 'name' => 'sebaya' ],
            [ 'name' => 'edukasi' ],
            [ 'name' => 'genre' ],
            [ 'name' => 'PIKR' ],
            [ 'name' => 'PIK-R' ],
            [ 'name' => 'PIK_R' ],
            [ 'name' => 'kespro' ],
            [ 'name' => 'gizi' ],
            [ 'name' => 'asertif' ],
            [ 'name' => 'PKBR' ],
            [ 'name' => 'BKR' ],
            [ 'name' => 'orang' ],
            [ 'name' => 'tua' ],
            [ 'name' => 'ortu' ],
            [ 'name' => 'BKL' ],
            [ 'name' => 'lansia' ],
            [ 'name' => 'tangguh' ],
            [ 'name' => 'perawatan' ],
            [ 'name' => 'kontrasepsi' ],
            [ 'name' => 'poster' ],
            [ 'name' => 'leaflet' ],
            [ 'name' => 'film' ],
            [ 'name' => 'lembar' ],
            [ 'name' => 'balik' ],
            [ 'name' => 'skata' ],
            [ 'name' => 'bimbingan' ],
            [ 'name' => 'catin' ],
            [ 'name' => 'caten' ],
            [ 'name' => 'stunting' ],
            [ 'name' => 'penyuluhan' ],
            [ 'name' => 'agama' ],
            [ 'name' => 'pengajian' ],
            [ 'name' => 'sekolah' ],
            [ 'name' => 'minggu' ],
            [ 'name' => 'ibadah' ],
            [ 'name' => 'perempuan' ],
            [ 'name' => 'perlindungan' ],
            [ 'name' => 'kekerasan' ],
            [ 'name' => 'MPASI' ],
            [ 'name' => 'makanan' ],
            [ 'name' => 'asap' ],
            [ 'name' => 'PKB' ],
            [ 'name' => 'PLKB' ],
            [ 'name' => 'IMP' ],
            [ 'name' => 'PPKBD' ],
            [ 'name' => 'SubPPKBD' ],
            [ 'name' => 'kader' ],
            [ 'name' => 'bumil' ],
            [ 'name' => 'PUS' ],
            [ 'name' => 'WUS' ],
            [ 'name' => 'pembinaan' ],
            [ 'name' => 'posyandu' ],
            [ 'name' => 'layanan' ],
            [ 'name' => 'PIL' ],
            [ 'name' => 'suntik' ],
            [ 'name' => 'IUD' ],
            [ 'name' => 'MOW' ],
            [ 'name' => 'MOP' ],
            [ 'name' => 'kondom' ],
            [ 'name' => 'implan' ],
            [ 'name' => 'implant' ],
            [ 'name' => 'susuk' ],
            [ 'name' => 'spiral' ],
            [ 'name' => 'PKH' ],
            [ 'name' => 'KPM' ],
        ]);
    }
}
